// <auto-generated />
using System;
using GameInventory.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameInventory.Infrastructure.Persistance.Migrations
{
    [DbContext(typeof(GameInventoryContext))]
    [Migration("20240820135746_AddTestData")]
    partial class AddTestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameInventory.Domain.Entities.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Format")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlatformId")
                        .HasColumnType("int");

                    b.Property<int?>("SeriesId")
                        .HasColumnType("int");

                    b.Property<int?>("StoreId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("PlatformId");

                    b.HasIndex("SeriesId");

                    b.HasIndex("StoreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Format = "Digital",
                            PlatformId = 6,
                            StoreId = 2,
                            Title = "Alan Wake 2"
                        },
                        new
                        {
                            Id = 2,
                            Format = "Physical",
                            PlatformId = 2,
                            Title = "Dark Chronicle"
                        },
                        new
                        {
                            Id = 3,
                            Format = "Physical",
                            PlatformId = 5,
                            SeriesId = 2,
                            Title = "Legend of Zelda: Breath of the Wild"
                        },
                        new
                        {
                            Id = 4,
                            Format = "Physical",
                            PlatformId = 5,
                            SeriesId = 1,
                            Title = "Super Mario Odyssey"
                        });
                });

            modelBuilder.Entity("GameInventory.Domain.Entities.Platform", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Platforms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "PS1"
                        },
                        new
                        {
                            Id = 2,
                            Name = "PS2"
                        },
                        new
                        {
                            Id = 3,
                            Name = "PS3"
                        },
                        new
                        {
                            Id = 4,
                            Name = "PS4"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Nintendo Switch"
                        },
                        new
                        {
                            Id = 6,
                            Name = "PC"
                        });
                });

            modelBuilder.Entity("GameInventory.Domain.Entities.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Series");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Super Mario"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ledgend Of Zelda"
                        });
                });

            modelBuilder.Entity("GameInventory.Domain.Entities.Store", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Stores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Steam"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Epic"
                        });
                });

            modelBuilder.Entity("GameInventory.Domain.Entities.Game", b =>
                {
                    b.HasOne("GameInventory.Domain.Entities.Platform", "Platform")
                        .WithMany()
                        .HasForeignKey("PlatformId");

                    b.HasOne("GameInventory.Domain.Entities.Series", "Series")
                        .WithMany()
                        .HasForeignKey("SeriesId");

                    b.HasOne("GameInventory.Domain.Entities.Store", "Store")
                        .WithMany()
                        .HasForeignKey("StoreId");

                    b.Navigation("Platform");

                    b.Navigation("Series");

                    b.Navigation("Store");
                });
#pragma warning restore 612, 618
        }
    }
}
